// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { supabase as mockSupabase } from './mock-client';

// ---------------------------------------------------------------------------
// PROTOTYPE MODE — set VITE_MOCK=true in .env to bypass real Supabase
// ---------------------------------------------------------------------------
const IS_MOCK = import.meta.env.VITE_MOCK === "true";

function createSupabaseClient() {
  // This client is browser-only. Server-side code must use client.server.ts.
  // Do NOT fall back to process.env here — passing JWT-bearing headers through
  // Vercel's undici fetch on the server causes an ISO-8859-1 header rejection.
  const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['VITE_SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['VITE_SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Connect Supabase in Lovable Cloud.`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

const realSupabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = IS_MOCK ? (mockSupabase as unknown as typeof realSupabase) : realSupabase;
